lib/guardian_auth_web/router.ex
defmodule GuardianAuthWeb.Router do
  use GuardianAuthWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource
  end

  pipeline :ensure_authed_access do
    plug Guardian.Plug.EnsureAuthenticated,handler: GuardianAuth.HttpErrorHandler
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GuardianAuthWeb do
    pipe_through [:browser,:browser_auth]
    resources "/sessions", SessionController, only: [:new, :create,:delete  ]
    resources "/users", UserController, only: [:new,:create]

  end


  scope "/", GuardianAuthWeb do
    pipe_through [:browser,:browser_auth,:ensure_authed_access]
    get "/", PageController, :index
    resources "/users", UserController, only: [:show, :index, :update,:edit,:delete]
  end

end

lib/guardian_auth_web/views/layout_view.ex
defmodule GuardianAuthWeb.LayoutView do
  use GuardianAuthWeb, :view
end

lib/guardian_auth_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Guardian Authentication Implementation and Sessions handling">
    <meta name="author" content="Blackode">

    <title>Hello GuardianAuth!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= render "sign_in_out.html", conn: @conn %>
          </ul>
        </nav>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/guardian_auth_web/templates/layout/sign_in_out.html.eex
<%= if logged_in?(@conn) do %>
  <li>
	<%= link "Sign out", to: session_path(@conn, :delete, current_user(@conn)),  method: :delete, class: "label label-danger" %><br>
    </li>
    <li>
	<%= link current_user(@conn).email, to: user_path(@conn,:show, current_user(@conn)), class: "label label-primary pull-right" %>
    </li>
<% else %>
  <li>
	<%= link "Create new account", to: user_path(@conn, :new), class: "label label-info" %>
    </li>
    <li>
	<%= link "Sign in", to: session_path(@conn, :new), class: "label label-info" %>
    </li>
<% end %>